// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zPIBui3U5QkHS8umiaymJUZNY_z6PMQ',
    appId: '1:511624257411:web:8d1ef52fed60aa16b0a0b6',
    messagingSenderId: '511624257411',
    projectId: 'app-remision-dd2ee',
    authDomain: 'app-remision-dd2ee.firebaseapp.com',
    storageBucket: 'app-remision-dd2ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnMfXctn9An0Dl3q4sruPW3bK2BomCSgc',
    appId: '1:511624257411:android:142a50dc98cbb058b0a0b6',
    messagingSenderId: '511624257411',
    projectId: 'app-remision-dd2ee',
    storageBucket: 'app-remision-dd2ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXu1JIwQVNxhoO-iOxY89-K0-FuJzlw2s',
    appId: '1:511624257411:ios:9e650c197b7b84dfb0a0b6',
    messagingSenderId: '511624257411',
    projectId: 'app-remision-dd2ee',
    storageBucket: 'app-remision-dd2ee.appspot.com',
    iosBundleId: 'com.example.appRemision',
  );
}
